### PR TITLE
LRDOCS-3957 wordsmithing

### PR DESCRIPTION
**Pull request by mwilliams2014**

### CODE REVIEW

**Comment by mwilliams2014** [comment]
@codyhoag Here is the updated PR for Javadoc review

**Comment by codyhoag** [comment]
Thanks, Mike! I'll try to get the formatter error figured out and get this back to you soon! I'll let you know!

**Comment by codyhoag** [comment]
FYI - I found a workaround to run the Javadoc Formatter on the class. I'll try and finish this review tomorrow. I filed the bug in [LPS-74636](https://issues.liferay.com/browse/LPS-74636). I alerted Andrea to it so hopefully it'll be fixed soon!

**Comment by codyhoag** [comment]
Sent mwilliams2014#4.

**Pull request closed without merging**
